# Generated by Django 2.2.3 on 2019-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payzant', '0002_auto_20190814_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAllStoresHardlines',
            fields=[
                ('plan', models.TextField(blank=True, db_column='Plan', null=True)),
                ('store', models.TextField(db_column='Store')),
                ('item_number', models.TextField(db_column='Item_Number')),
                ('description', models.TextField(db_column='Description')),
                ('date_added', models.DateField(blank=True, db_column='Date_Added', null=True)),
                ('rop_protect', models.TextField(blank=True, db_column='ROP_Protect', null=True)),
                ('proxy_only', models.TextField(blank=True, db_column='Proxy_Only', null=True)),
                ('popularity', models.TextField(blank=True, db_column='Popularity', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('location_2', models.TextField(blank=True, db_column='Location_2', null=True)),
                ('location_3', models.TextField(blank=True, db_column='Location_3', null=True)),
                ('order_point', models.FloatField(blank=True, db_column='Order_Point', null=True)),
                ('order_point_a', models.FloatField(blank=True, db_column='Order_Point_A', null=True)),
                ('order_point_b', models.FloatField(blank=True, db_column='Order_Point_B', null=True)),
                ('order_point_c', models.FloatField(blank=True, db_column='Order_Point_C', null=True)),
                ('order_point_d', models.FloatField(blank=True, db_column='Order_Point_D', null=True)),
                ('min_order_point', models.FloatField(blank=True, db_column='Min_Order_Point', null=True)),
                ('imu_safety_stock', models.FloatField(blank=True, db_column='IMU_Safety_Stock', null=True)),
                ('rule_used', models.TextField(blank=True, db_column='Rule_Used', null=True)),
                ('new_order_point', models.FloatField(blank=True, db_column='New_Order_Point', null=True)),
                ('projected_order_point', models.FloatField(blank=True, db_column='Projected_Order_Point', null=True)),
                ('qoh', models.FloatField(blank=True, db_column='QOH', null=True)),
                ('average_qoh', models.FloatField(blank=True, db_column='Average_QOH', null=True)),
                ('retail_price', models.FloatField(blank=True, db_column='Retail_Price', null=True)),
                ('average_cost', models.FloatField(blank=True, db_column='Average_Cost', null=True)),
                ('replacement_cost', models.FloatField(blank=True, db_column='Replacement_Cost', null=True)),
                ('inv_value', models.FloatField(blank=True, db_column='Inv_Value', null=True)),
                ('new_inv_value', models.FloatField(blank=True, db_column='New_Inv_Value', null=True)),
                ('value_change', models.FloatField(blank=True, db_column='Value_Change', null=True)),
                ('lead_time_count', models.FloatField(blank=True, db_column='Lead_Time_Count', null=True)),
                ('forecast_model_used', models.TextField(blank=True, db_column='Forecast_Model_Used', null=True)),
                ('forecast_demand_per_day', models.FloatField(blank=True, db_column='Forecast_Demand_Per_Day', null=True)),
                ('total_days_of_supply', models.FloatField(blank=True, db_column='Total_Days_Of_Supply', null=True)),
                ('days_of_supply_required', models.FloatField(blank=True, db_column='Days_Of_Supply_Required', null=True)),
                ('demand_adjustment_factor', models.FloatField(blank=True, db_column='Demand_Adjustment_Factor', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_all_stores_hardlines',
                'managed': False,
            },
        ),
    ]
